apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: challenge-ingress-{{instance_id}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: challenge-{{instance_id}}.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: challenge-service-{{instance_id}}
            port:
              number: 80
