apiVersion: v1
kind: Service
metadata:
  name: challenge-service-{{instance_id}}
spec:
  selector:
    app: challenge
    instance: {{instance_id}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
