version: '3.9'

services:
  web:
    build: .
    command: ./entrypoint.sh
    container_name: ctf-backend
    restart: always
    network_mode: "host"
    volumes:
      - ./static:/code/static
      - ./media:/code/media
      - ../k3s.yaml:/root/.kube
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: ctf-db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  mysql_data:
